id: P001720
initial_creation_type: ocr
source_metadata:
  id: bdr:W29517
  title: འབྲུག་པ་ཀུན་ལེགས་ཀྱི་རྣམ་ཐར།
  author: ''
  volumes:
    836780a8dadb435aaacd9cf1441b1ca2:
      image_group_id: I00EGS1017356
      title: ''
      volume_number: 1
      total_pages: 578
